config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # get 'bookmark/new'
  # get 'bookmark/create'
  # get 'bookmark/destroy'
  # get 'lists/index'
  # get 'lists/show'
  # get 'lists/new'
  # get 'lists/create'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new,:create]
    resources :reviews, only: :create
  end

  resources :bookmarks, only: [:destroy]
  resources :lists, only: [:destroy]
  resources :reviews, only: [:destroy]

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :movie_id, uniqueness: {scope: :list_id, message: "is already in the list"}
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  mount_uploader :photo, ImageUploader
  has_one_attached :photo

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :lists, through: :bookmarks
  validates :title, :overview, uniqueness: true, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]
  before_action :set_list, only: [:show]


  def new
    # @bookmark = Bookmark.new
    # @movies = Movie.all
  end

   def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to @list, notice: 'Movie was successfully added to the list.'
    else
      render 'lists/show'
    end
  end


  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other

  end

 private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @Bookmark = Bookmark.find(params[:bookmark_id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    if params[:search].present?
      search_query = params[:search]
      @movies = Movie.where("title ILIKE ?", "%#{search_query}%").sort_by { |movie| movie.title.casecmp(search_query) }
    else
      @movies = Movie.all
    end
    @lists = List.all
  end



  def show
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
    @review = Review.new


  end

  def new
    @list = List.new
    @list.photo = params[:file]
  end

  def create
    @list = List.new(list_params)
    list.photo = params[:list][:photo]


    raise
    if @list.save
      redirect_to list_path(@list), notice: "list successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    @list.destroy
    redirect_to lists_path(@list), status: :see_other
  end
  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:destroy]


  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list

    if @review.save
      redirect_to list_path(@list), notice: "review successfully added"
    else
      @bookmark = Bookmark.new
      render 'show/list', status: :unprocessable_entity
    end
  end

  def destroy
    @reviews.destroy
    redirect_to list_path(@review.list)
  end


  private

    def set_review
      @review = Review.find(param[:id])
    end

    def review_params
      params.require(:review).permit(:comment, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_modal.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%= simple_form_for [list, bookmark] do |f| %>
        <div class="modal-body">
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add movie", class: "btn btn-flat" %>
          <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<h1>Add Movie to List</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie, collection: Movie.all %>
  <%= f.input :comment %>
  <%= f.button :submit, 'Add Movie' %>
<% end %>

<%= link_to "Back to List", list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>

  <footer>
  <%= render 'shared/footer' %>
  </footer>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="search">
      <%= form_tag(@movies_path, method: :get) do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search movies", class:"input" %>
        <%= submit_tag "Search", class:"submit" %>
      <% end %>
  </div>
    <% if params[:search].present? %>
    <h2>Search Results:</h2>
      <% if @movies.any? %>
        <div class="movie-list">
          <% @movies.each do |movie| %>
            <div>
              <%= movie.title %>
            </div>
          <% end %>
        </div>
      <% else %>
        <p>No movies found.</p>
      <% end %>
    <% end %>
</div>


<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-flat", "data-controller" => "desable_button" %>


  </div>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="co-12 col-sm-6 col-md-4 mb-3">
        <%= link_to list_path(list), class:"text-decoration-none" do %>
           <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.url.present? ? list.photo.url : asset_path('list_background.jpg') %>)">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h3>Create a new list</h3>

<div class="container py-5">
  <div class="row">
    <div class="col-3 p-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
           <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="position-relative">
  <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.url.present? ? cl_image_path(@list.photo.url) : asset_path('list_background.jpg') %>)">

    <h1><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>
<div class="container py-5">
   <div >
   <%# class="d-flex align-items-center justify-content-between" %>
    <h3 class="mb-0">My List</h3>
    <h4> <%= @list.name %></h4>
    <%= @list.movies.count %> movies in the list
  </div>
 <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-4 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, height: 300, crop: :fill, alt: movie.title, class: "movie-img rounded-top" %>
           <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
    <%= link_to "Remove this list", list_path(@list), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    <hr></hr>
  <h2>Add Movie:</h2>

    <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: Movie.all %>
    <%= f.input :comment %>
    <%= f.button :submit, 'Add Movie' %>
  <% end %>

  <%= link_to "Back to Lists", lists_path %>

 <hr class="my-5">
  <div class="row">
   <%= render "reviews/form", review: @review %>
  </dir>
</div>


<!-- Display flash messages -->
<% flash.each do |key, message| %>
  <div class="<%= key %>"><%= message %></div>
<% end %>

app/views/reviews/_form.html.erb
<div class="col-12 col-sm-6">
  <h3>Reviews</h3>
  <% if @list.reviews.empty? %>
    <small><em class="text-muted">Be the first one to review this list</em></small>
  <% end %>
  <% @list.reviews.each do |review| %>
    <div>
      <% review.rating.times do %>
        <i class="fas fa-star star-yellow"></i>
      <% end %>
      <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
      <p class="mb-0"><%= review.comment %></p>
    </div>
    <hr>
  <% end %>
</div>

<div class="col-12 col-sm-6">
  <div class="bg-white rounded p-3">
    <h5>Add your review</h5>
    <%= simple_form_for [@list, @review] do |f| %>
      <%= f.input :comment, placeholder: "Add your review here...", class: "form-control" %>
      <%= f.input :rating, as: :select, collection: (1..5), required: true, label: false, input_html: { class: "form-control" } %>
      <%= f.submit "Submit Review", class: "btn btn-primary mt-2" %>
    <% end %>
  </div>
</div>

app/views/reviews/_modal.html.erb
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a movie </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie, collection: Movie.all %>
        <%= f.input :comment %>
        <%= f.button :submit, 'Add Movie' %>
      <% end %>

        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="col 12 p-3">
  <div class="bg white rounded p-3">
    <h1>Add your Reviews</h1>
    <%= simple_form_for @list @review do |f| %>
      <%= f.input :comment, placeholder: "Add your review here..." %>
      <%= f.input :rating, as: :select, collection: (1..5), required: true, label: false, input_html: { data: { controller: "star-rating" } } %>
      <%= f.submit "Create Review" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="images/popcorn.jpg" alt="">

</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Messages</a>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>